In [3]:
import pandas as pd
import numpy as np

In [3]:
browsing = pd.read_csv("D:/Downloads/SIGIR-ecom-data-challenge/train/browsing_train.csv")
search = pd.read_csv("D:/Downloads/SIGIR-ecom-data-challenge/train/search_train.csv")
products = pd.read_csv("D:/Downloads/SIGIR-ecom-data-challenge/train/sku_to_content.csv")

In [5]:
search = pd.read_csv("D:/Downloads/SIGIR-ecom-data-challenge/train/search_train.csv")

In [18]:
browsing.head()

,session_id_hash,event_type,product_action,product_sku_hash,server_timestamp_epoch_ms,hashed_url
0,20c458b802f6ea9374783bfc528b19421be977a6769785...,event_product,detail,d5157f8bc52965390fa21ad5842a8502bc3eb8b0930f3f...,1550885210881,7e4527ac6a32deed4f4f06bb7c49b907b7ca371e59d57d...
1,20c458b802f6ea9374783bfc528b19421be977a6769785...,event_product,detail,61ef3869355b78e11011f39fc7ac8f8dfb209b3442a9d5...,1550885213307,4ed279f4f0deab6dfc80f4f7bf49d527fd894fa478a9ce...
2,20c458b802f6ea9374783bfc528b19421be977a6769785...,pageview,NaN,NaN,1550885213307,4ed279f4f0deab6dfc80f4f7bf49d527fd894fa478a9ce...
3,20c458b802f6ea9374783bfc528b19421be977a6769785...,event_product,detail,d5157f8bc52965390fa21ad5842a8502bc3eb8b0930f3f...,1550885215484,7e4527ac6a32deed4f4f06bb7c49b907b7ca371e59d57d...
4,20c458b802f6ea9374783bfc528b19421be977a6769785...,pageview,NaN,NaN,1550885215484,7e4527ac6a32deed4f4f06bb7c49b907b7ca371e59d57d...

In [17]:
browsing.shape

(36079307, 6)

In [22]:
browsing.columns

Index(['session_id_hash', 'event_type', 'product_action', 'product_sku_hash',
       'server_timestamp_epoch_ms', 'hashed_url'],
      dtype='object')

In [24]:
browsing.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36079307 entries, 0 to 36079306
Data columns (total 6 columns):
 #   Column                     Dtype
---  ------                     -----
 0   session_id_hash            object
 1   event_type                 object
 2   product_action             object
 3   product_sku_hash           object
 4   server_timestamp_epoch_ms  int64
 5   hashed_url                 object
dtypes: int64(1), object(5)
memory usage: 1.6+ GB

In [28]:
search.head()

,session_id_hash,query_vector,clicked_skus_hash,product_skus_hash,server_timestamp_epoch_ms
0,48fade624d47870058ce07dd789ccc04e46c70c0fa2a1b...,"[-0.20255649089813232, -0.016908567398786545, ...",NaN,NaN,1548575194779
1,8731ca84ff7bb8cb647531d54e64feedb2519b4a7792a7...,"[-0.007610442116856575, -0.14909175038337708, ...",NaN,['9ee9ffd7e2529a65f9a0b0c9eaae6330df85cf2e3af3...,1548276763869
2,9be980708345944960645d03606ea83b637cae9106b705...,"[-0.20023074746131897, -0.03151938319206238, 0...",NaN,['7cc72dbed53bab78ec6a62feaa5052a7a1db7d201664...,1548937997295
3,9be980708345944960645d03606ea83b637cae9106b705...,"[-0.18556387722492218, -0.07620412111282349, 0...",NaN,['62c4ddab6c1c81c74d315376b3c0dc7768c0286b3dc6...,1548938038268
4,9be980708345944960645d03606ea83b637cae9106b705...,"[-0.03269264101982117, -0.27234694361686707, 0...",NaN,['2a0ee2924feabeec35e21e8fcb4d5b0684d190e46cef...,1548938093827

In [32]:
search.shape

(819516, 5)

In [34]:
search.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 819516 entries, 0 to 819515
Data columns (total 5 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   session_id_hash            819516 non-null  object
 1   query_vector               819516 non-null  object
 2   clicked_skus_hash          179495 non-null  object
 3   product_skus_hash          602754 non-null  object
 4   server_timestamp_epoch_ms  819516 non-null  int64
dtypes: int64(1), object(4)
memory usage: 31.3+ MB

In [36]:
products.head()

,product_sku_hash,description_vector,category_hash,image_vector,price_bucket
0,26ce7b47f4c46e4087e83e54d2f7ddc7ea57862fed2e2a...,NaN,NaN,NaN,NaN
1,6383992be772b204a9ab75f86c86f5583d1bdd1222952d...,NaN,NaN,NaN,NaN
2,a2c3e2430c6ef9770b903ad08fa067a6b2b9db28f06e1b...,"[0.27629122138023376, -0.15763211250305176, 0....",06fa312761d4b39e2f649781514ac69a4c1505c221fc46...,"[340.3592564184389, -220.19025864725685, 154.0...",7.0
3,1028ef615e425c328e7b95010dfb1fb93cf63749a1bc80...,"[0.4058118760585785, -0.03595402091741562, 0.2...",115a6a7017ee55752b8487c77dfde92b0d501d10a2e69c...,"[180.3463662921092, 222.702322343354, -8.88703...",8.0
4,9870c682d0d52d635501249da0eeaa118fad430b695ea1...,"[-0.3206155300140381, 0.01991105079650879, 0.0...",0665a81d19c89281cc00e7f7d779ded2ed42c933838602...,"[-114.81079301576219, 84.55770104232334, 85.51...",2.0

In [38]:
products.shape

(66386, 5)

In [40]:
products.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 66386 entries, 0 to 66385
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   product_sku_hash    66386 non-null  object
 1   description_vector  31950 non-null  object
 2   category_hash       32052 non-null  object
 3   image_vector        28370 non-null  object
 4   price_bucket        32038 non-null  float64
dtypes: float64(1), object(4)
memory usage: 2.5+ MB

In [42]:
browsing.isnull().sum()

session_id_hash                     0
event_type                          0
product_action               25647696
product_sku_hash             25647696
server_timestamp_epoch_ms           0
hashed_url                          0
dtype: int64

In [44]:
search.isnull().sum()

session_id_hash                   0
query_vector                      0
clicked_skus_hash            640021
product_skus_hash            216762
server_timestamp_epoch_ms         0
dtype: int64

In [47]:
products.isnull().sum()

product_sku_hash          0
description_vector    34436
category_hash         34334
image_vector          38016
price_bucket          34348
dtype: int64

In [51]:
browsing["event_type"].value_counts(dropna=False)

event_type
pageview         25647696
event_product    10431611
Name: count, dtype: int64

In [53]:
browsing["product_action"].value_counts(dropna=False)

product_action
NaN         25647696
detail       9707890
add           329557
remove        316316
purchase       77848
Name: count, dtype: int64

In [55]:
search["clicked_skus_hash"].isna().value_counts()

clicked_skus_hash
True     640021
False    179495
Name: count, dtype: int64

In [57]:
search["product_skus_hash"].isna().value_counts()

product_skus_hash
False    602754
True     216762
Name: count, dtype: int64

In [59]:
products.isna().sum()

product_sku_hash          0
description_vector    34436
category_hash         34334
image_vector          38016
price_bucket          34348
dtype: int64

In [65]:
pd.crosstab(
    browsing["event_type"],
    browsing["product_action"],
    dropna=False
)

product_action     add   detail  purchase  remove       NaN
event_type
event_product   329557  9707890     77848  316316         0
pageview             0        0         0       0  25647696

In [67]:
pd.crosstab(
    browsing["event_type"],
    browsing["product_sku_hash"].isna()
)

product_sku_hash     False     True
event_type
event_product     10431611         0
pageview                 0  25647696

In [69]:
pd.crosstab(
    search["product_skus_hash"].isna(),
    search["clicked_skus_hash"].isna()
)

clicked_skus_hash   False   True
product_skus_hash
False              179372  423382
True                  123  216639

In [71]:
search[
    search["clicked_skus_hash"].notna()
][["product_skus_hash", "clicked_skus_hash"]].head(10)

,product_skus_hash,clicked_skus_hash
12,['6c792545216e765efc2cfb6173fa17f833436116c703...,['20e8f1c4051a6c55122bd00f25f92f91b5f125497b79...
13,['730383c6329e2e6d7a4cffe641414abaab78da9d1858...,['8283e8b59c283c3b72462a6f73084683524f4b0149ac...
18,['12db169815cb93aaeeb1d427d6c0eea62ba4961e43c4...,['2901d00c55fc2e4e60ea0d0e7a48ee843491e31025af...
19,['956c335d2f59c1853f499420ae4e85250a6c7190a1df...,['3983d0cd10e567317005f8f47d3592beb8aceeca2dcb...
22,['956c335d2f59c1853f499420ae4e85250a6c7190a1df...,['ea64b218fb45c07968ebc85129b2dfe4b22f83176c98...
31,['da8685972526b9b7801581203c17225f8549edd2ae6a...,['f30cb893bc3200b544c486d7332bf1c6d0598ddf9ed3...
32,['0c64a150a3b498351a0d1382a12442dea8c399ffc38b...,['b671fc9d0481cb8decdd2e9d0e460a22f87af3e93fd0...
43,['7b023d6c0c025887642f7ad0659016e9c6abde476c3d...,['d125edf4996f67adccefbaa16f1bffa7e331a835dba5...
45,['57d3109143f8518172f3b5ee7bacaaadd32a8d5f9955...,['040998a67f386a3bb027ffc119b37049eb0a0c691ac9...
46,['a18b4d276a8ee9e5586e07bced4c4b695391b1083052...,['8b8228722bbe9ecfeed4c40d8e00e09a7446bca70da8...

In [73]:
search[
    search["product_skus_hash"].notna()
][["product_skus_hash", "clicked_skus_hash"]].head(10)

,product_skus_hash,clicked_skus_hash
1,['9ee9ffd7e2529a65f9a0b0c9eaae6330df85cf2e3af3...,NaN
2,['7cc72dbed53bab78ec6a62feaa5052a7a1db7d201664...,NaN
3,['62c4ddab6c1c81c74d315376b3c0dc7768c0286b3dc6...,NaN
4,['2a0ee2924feabeec35e21e8fcb4d5b0684d190e46cef...,NaN
5,['62c4ddab6c1c81c74d315376b3c0dc7768c0286b3dc6...,NaN
6,['62c4ddab6c1c81c74d315376b3c0dc7768c0286b3dc6...,NaN
7,['56e9531819044bb70b80b2e3f798dbd4f71b08cd7a1a...,NaN
11,['710dc33ed61ae82db5ac89e11dfae101f168a35bc9f9...,NaN
12,['6c792545216e765efc2cfb6173fa17f833436116c703...,['20e8f1c4051a6c55122bd00f25f92f91b5f125497b79...
13,['730383c6329e2e6d7a4cffe641414abaab78da9d1858...,['8283e8b59c283c3b72462a6f73084683524f4b0149ac...

In [75]:
search["clicked_skus_hash"].dropna().head(20).tolist()

["['20e8f1c4051a6c55122bd00f25f92f91b5f125497b793923c3158b48247fd0f0']",
 "['8283e8b59c283c3b72462a6f73084683524f4b0149acb746d80857ee5e765193']",
 "['2901d00c55fc2e4e60ea0d0e7a48ee843491e31025afaba2aabd4dbbe33d0485', 'f706d1c864e7153a637add15e2bbb25fb8a1e3eb04c5100e446d874fab39d45f']",
 "['3983d0cd10e567317005f8f47d3592beb8aceeca2dcb28080b8bebc3099fb395']",
 "['ea64b218fb45c07968ebc85129b2dfe4b22f83176c98808f49534e58ef82f8eb']",
 "['f30cb893bc3200b544c486d7332bf1c6d0598ddf9ed361c32a13ca51b4215786']",
 "['b671fc9d0481cb8decdd2e9d0e460a22f87af3e93fd08ae0f0d1481090cb5823']",
 "['d125edf4996f67adccefbaa16f1bffa7e331a835dba5fbc67557179e725b802b']",
 "['040998a67f386a3bb027ffc119b37049eb0a0c691ac902d45711308bc65747e5']",
 "['8b8228722bbe9ecfeed4c40d8e00e09a7446bca70da8197fc959c303fec6d396', '8b8228722bbe9ecfeed4c40d8e00e09a7446bca70da8197fc959c303fec6d396']",
 "['4ef87961353b8e3082da2101e516941ee56b23af933862fa0a919f55169b375d']",
 "['f72bb782fb622186dea1bde580997b78cbbdae4806ec6bbfa7a9b1393107f770']",
 "['4991ea35d9d53dea7d3785c07218967dbb1f61ea30e331bcbdf081af4793e738', '4991ea35d9d53dea7d3785c07218967dbb1f61ea30e331bcbdf081af4793e738', '4991ea35d9d53dea7d3785c07218967dbb1f61ea30e331bcbdf081af4793e738', '4991ea35d9d53dea7d3785c07218967dbb1f61ea30e331bcbdf081af4793e738', '4991ea35d9d53dea7d3785c07218967dbb1f61ea30e331bcbdf081af4793e738', '4991ea35d9d53dea7d3785c07218967dbb1f61ea30e331bcbdf081af4793e738', '4991ea35d9d53dea7d3785c07218967dbb1f61ea30e331bcbdf081af4793e738', '4991ea35d9d53dea7d3785c07218967dbb1f61ea30e331bcbdf081af4793e738', '4991ea35d9d53dea7d3785c07218967dbb1f61ea30e331bcbdf081af4793e738', '4991ea35d9d53dea7d3785c07218967dbb1f61ea30e331bcbdf081af4793e738', '4991ea35d9d53dea7d3785c07218967dbb1f61ea30e331bcbdf081af4793e738', '4991ea35d9d53dea7d3785c07218967dbb1f61ea30e331bcbdf081af4793e738', '4991ea35d9d53dea7d3785c07218967dbb1f61ea30e331bcbdf081af4793e738', '4991ea35d9d53dea7d3785c07218967dbb1f61ea30e331bcbdf081af4793e738', '4991ea35d9d53dea7d3785c07218967dbb1f61ea30e331bcbdf081af4793e738', '4991ea35d9d53dea7d3785c07218967dbb1f61ea30e331bcbdf081af4793e738', '4991ea35d9d53dea7d3785c07218967dbb1f61ea30e331bcbdf081af4793e738', '4991ea35d9d53dea7d3785c07218967dbb1f61ea30e331bcbdf081af4793e738', '4991ea35d9d53dea7d3785c07218967dbb1f61ea30e331bcbdf081af4793e738', '4991ea35d9d53dea7d3785c07218967dbb1f61ea30e331bcbdf081af4793e738', '4991ea35d9d53dea7d3785c07218967dbb1f61ea30e331bcbdf081af4793e738', '4991ea35d9d53dea7d3785c07218967dbb1f61ea30e331bcbdf081af4793e738', '4991ea35d9d53dea7d3785c07218967dbb1f61ea30e331bcbdf081af4793e738', '4991ea35d9d53dea7d3785c07218967dbb1f61ea30e331bcbdf081af4793e738', '4991ea35d9d53dea7d3785c07218967dbb1f61ea30e331bcbdf081af4793e738', '4991ea35d9d53dea7d3785c07218967dbb1f61ea30e331bcbdf081af4793e738', '4991ea35d9d53dea7d3785c07218967dbb1f61ea30e331bcbdf081af4793e738', '4991ea35d9d53dea7d3785c07218967dbb1f61ea30e331bcbdf081af4793e738', '4991ea35d9d53dea7d3785c07218967dbb1f61ea30e331bcbdf081af4793e738', '4991ea35d9d53dea7d3785c07218967dbb1f61ea30e331bcbdf081af4793e738', '4991ea35d9d53dea7d3785c07218967dbb1f61ea30e331bcbdf081af4793e738', '4991ea35d9d53dea7d3785c07218967dbb1f61ea30e331bcbdf081af4793e738', '4991ea35d9d53dea7d3785c07218967dbb1f61ea30e331bcbdf081af4793e738', '4991ea35d9d53dea7d3785c07218967dbb1f61ea30e331bcbdf081af4793e738', '4991ea35d9d53dea7d3785c07218967dbb1f61ea30e331bcbdf081af4793e738', '4991ea35d9d53dea7d3785c07218967dbb1f61ea30e331bcbdf081af4793e738', '4991ea35d9d53dea7d3785c07218967dbb1f61ea30e331bcbdf081af4793e738', '4991ea35d9d53dea7d3785c07218967dbb1f61ea30e331bcbdf081af4793e738', '4991ea35d9d53dea7d3785c07218967dbb1f61ea30e331bcbdf081af4793e738', '4991ea35d9d53dea7d3785c07218967dbb1f61ea30e331bcbdf081af4793e738', '4991ea35d9d53dea7d3785c07218967dbb1f61ea30e331bcbdf081af4793e738', '4991ea35d9d53dea7d3785c07218967dbb1f61ea30e331bcbdf081af4793e738', '4991ea35d9d53dea7d3785c07218967dbb1f61ea30e331bcbdf081af4793e738', '4991ea35d9d53dea7d3785c07218967dbb1f61ea30e331bcbdf081af4793e738', '4991ea35d9d53dea7d3785c07218967dbb1f61ea30e331bcbdf081af4793e738', '4991ea35d9d53dea7d3785c07218967dbb1f61ea30e331bcbdf081af4793e738', '4991ea35d9d53dea7d3785c07218967dbb1f61ea30e331bcbdf081af4793e738', '4991ea35d9d53dea7d3785c07218967dbb1f61ea30e331bcbdf081af4793e738', '4991ea35d9d53dea7d3785c07218967dbb1f61ea30e331bcbdf081af4793e738', '4991ea35d9d53dea7d3785c07218967dbb1f61ea30e331bcbdf081af4793e738', '4991ea35d9d53dea7d3785c07218967dbb1f61ea30e331bcbdf081af4793e738', '4991ea35d9d53dea7d3785c07218967dbb1f61ea30e331bcbdf081af4793e738', '4991ea35d9d53dea7d3785c07218967dbb1f61ea30e331bcbdf081af4793e738', '4991ea35d9d53dea7d3785c07218967dbb1f61ea30e331bcbdf081af4793e738', '4991ea35d9d53dea7d3785c07218967dbb1f61ea30e331bcbdf081af4793e738', '4991ea35d9d53dea7d3785c07218967dbb1f61ea30e331bcbdf081af4793e738']",
 "['aa887e363bd37ebafed78d60f3f076773fcec1ad1b789d9526eff5607d7b4fe2', 'aa887e363bd37ebafed78d60f3f076773fcec1ad1b789d9526eff5607d7b4fe2', '2db4ae33ab95f77613f43096d748651c6aebbf4fb01b3aed5faba39178c50cf6']",
 "['b3ad69151e8f0652e665696c5f7f50e77f6a3887935fc4452423718ae3bc10e0', '43c032357cb2ec51ac33bbbed47e547f01b3de9793da2a77243f290d4f6f5075', 'a016a55fef0a2a30d979186f8882b361057e57deab2bbe66196bd48adca69045']",
 "['53c5c9d0002590596ce079639cc39b075f185fd5a1c50bfcd1b6cff9e788f790', 'a4ccb08c402c8875de1401cd230d16263d1dcdf27af3bee59cc436f7a315e2bb', '62f6a294af99e8ca76d02a3607281f7bf5b435fb6b0a1b9b23dfa0a391df3e2c', '56292148482e47f693de8a0374d62a1f6b639895b7efc40efac89280a3e5177f', 'ee4fbf5932db0ed31fa363e740a791efd82dc5c8e4974cc0ae0ecae387302089', '05f189e0d339fc48d99c45d6f611bdb3593d64429e51781f2c72c8f9116ea915', '593ba2efacc8523f92aab5ce48574ec8ab7bd00d7e203d70eb587766c7fb458a', '62f6a294af99e8ca76d02a3607281f7bf5b435fb6b0a1b9b23dfa0a391df3e2c']",
 "['988a0e9a2638f7f158350d05eac12cf1007b42aef8d4794ae92f65d17c1a5191', 'b7d58a895b2065d7c1cbe4e37e8f579592493f7c6db6957362fb972f0af8fe0d']",
 "['988a0e9a2638f7f158350d05eac12cf1007b42aef8d4794ae92f65d17c1a5191']",
 "['4dfdcc46a277ec6d15bb00792b96056108cb318d073988fc52b2758fa5e5b2ac']",
 "['9f55d787c48dcc69536c07cb41cf11b28bdd90cd3821562275b8cddb58717594']"]

In [77]:
search["product_skus_hash"].dropna().head(5).tolist()

["['9ee9ffd7e2529a65f9a0b0c9eaae6330df85cf2e3af33ef58dcf70fb5856c86a', '4367f3b54eded7d6f8800a381dec2970e3751dc9c14a1be6861ce25347662994', '54f0f45519bbff585a55899d88e4cca03e61b88f90783edf17454131f9a5bb73']",
 "['7cc72dbed53bab78ec6a62feaa5052a7a1db7d201664bb8d23ed55b68cfe43e2', '3da7ad7f203d5ed2dfb6db08065266fa49c700e028e8bb447c8386a80460fa30', '664fae425faebb61c083606e059bf6e28cc86adcd047fd2b08f52fd06235bb27', '05924a7ed72204fbde3a21d7833da2ee23a9dff7a8e2715514e8365e866d949a', 'f0ff35ed8a1feb70e2a5d1ec178fae47452177815ef5d76996b50de6e67daa64', 'bd2f17bff45a72e4c9d7f5916dd930a87bffc8046cc86f37f0dae510b12e3ce2', 'd627da3aba5e8a7a6fba3e9774fd896fd163a3fd284d447e0a460adc37846284']",
 "['62c4ddab6c1c81c74d315376b3c0dc7768c0286b3dc6f14d23d947a96f8f08f0', 'e05cd95cd5bbf9452dc76e5c097d928b7b8a21a553bd32ac84890e3c27a91a50', '18d0cbb6fcd4c67c6e4a863ab86a18bd4f2558e8b0b92f63b37507cdd27b99a4', 'c7f9523426ecc6ce5d988966f36c906d04e84006c90753cf2b7273bece7f1253', '1378d1490ae96c2e576db5d78e1640d863d64e97b08410187bc8202bee3c7e51', '30c66a2327b0c1426eda7692de92b6ee3d3aa53bade2710f5878fc46e6f513d8', 'f6ec1b20eac2a3f3cfc580d14ae5a47ca80642d0545dc91ea10c184f13efc683', '08159904b78aa3502e211661ee2fd972d6fdb15afd1e04a431b8d745db667a04', '43a258d5f864cf1977bbd5878a0be6ace9cc8d0bbe3e6b9469ccff690a785309', '92336743a91d962e44a7dd38c987b7c89a1379759516dda511650b405b53ef2f', 'b6bb9ab5d1ee92ee0f56aee23ab8d6f65d79ea5ee7bc37816f177be0bb560b93', '24b3f86293cd4fa0455d9adc2e3a0753c3a1fa75628058eb049006e345bf2f11', '3dc41b928418cedc8bee60dcba3b2e11aed7db0dadf98cb357df44567eef790e']",
 "['2a0ee2924feabeec35e21e8fcb4d5b0684d190e46cef7677297a840d453bed36', '9d5da686bb9c0221ebbbf9f58a6831803e60f4f9d312cc2bd6ac49f8fbb37ec2', '42f96b5e7f707afa94e22c3c466bcc9ddf27e3635b408fa109a4265a16ae08db', '920744baab1b72aa10744f4e9917ee1adc17a0d03b50f07fed822b6d94dad113', '3a9740509fc13f3af2c3615b1c26d86ff8d37dbfdf87b5ca83415b443619fcb2', '312882833ec43db8aacc896311529f81bf962227029a2366bc5179fa57a8c8fb', '14ce43dd429f7a141376861ed041c52dc54e9a6899a1428a540619d32dc23c29', '87efeae2973479978a401541e4dbf006084e522ecb13bdc92e47519fe56cd1b2', 'bae218fe5752f525051bcc409014a3023adccd1d377390a74401c9200ee314a8', '981325101a8ed7cd2d6d99a4731f57356cc065bb17aecaf400d2d0772bc0678a', 'dac7991065cc4a3bba6665b778b96d0b1f0c4d80067ff6d41cd2c07c61fc7c5f', '860ea84120a40fed025bc27178c3499d3a7941ca5a6534d1e4e0b801c33d56c2', '6092c8306d973fa297a1fb225f15a261e298f920fd86d4bb156c0a324d2d70e8', '52a27241e700bc9f5e3806a7a3632b693d4a17164ded1998fd93de6b4b37c5b3', '6a74de87edb81e74ffb175153365e017d1375d7f388091db0840d6913c4e0732', 'fb835639a130b4393c3fd425aec84a862673991479fe3cbb85c7368696d735b7', '58174f02b63fc1be720e9ccc3e6ba7e9be0e731159877f8a91f141af511a3061', '3ed95787a53df1fe89df26b08f518ce9a42c701aa76f3d77b23235d10a01b0db', '9b154bca618e3e956fa3c36a03bb1c1d6739c927edef6b56e1f12ae844485cdd', '09bbb519923bacecc0c793d09bb21c9e52fdc923b4e35be43683df8c3de32f54', '11204f9fa3590bb4e284d51a377f60e153f3a56f592a11128284b95a014ed88c', 'fe731567e08b298f5d9a4c232e961aec686cb5d171b3dbd40c5396ddab2e748b', '0626355814b235eee38e4c8fc1ac80fbb150f8741026829c853e455b5de4d413', '3a040495dba80c5edb33e2f53fbd696e7a3f77b55bd8bd3f25f186efc606314c', '64fa2ae0446ca0d5e60e4dde09641592d89832493f5867b546c8988d7bb71d12']",
 "['62c4ddab6c1c81c74d315376b3c0dc7768c0286b3dc6f14d23d947a96f8f08f0', 'e05cd95cd5bbf9452dc76e5c097d928b7b8a21a553bd32ac84890e3c27a91a50', '18d0cbb6fcd4c67c6e4a863ab86a18bd4f2558e8b0b92f63b37507cdd27b99a4', 'c7f9523426ecc6ce5d988966f36c906d04e84006c90753cf2b7273bece7f1253', '1378d1490ae96c2e576db5d78e1640d863d64e97b08410187bc8202bee3c7e51', '30c66a2327b0c1426eda7692de92b6ee3d3aa53bade2710f5878fc46e6f513d8', 'f6ec1b20eac2a3f3cfc580d14ae5a47ca80642d0545dc91ea10c184f13efc683', '08159904b78aa3502e211661ee2fd972d6fdb15afd1e04a431b8d745db667a04', '43a258d5f864cf1977bbd5878a0be6ace9cc8d0bbe3e6b9469ccff690a785309', '92336743a91d962e44a7dd38c987b7c89a1379759516dda511650b405b53ef2f', 'b6bb9ab5d1ee92ee0f56aee23ab8d6f65d79ea5ee7bc37816f177be0bb560b93', '24b3f86293cd4fa0455d9adc2e3a0753c3a1fa75628058eb049006e345bf2f11', '3dc41b928418cedc8bee60dcba3b2e11aed7db0dadf98cb357df44567eef790e']"]

In [4]:
import ast

product_lists = search["product_skus_hash"].dropna().apply(ast.literal_eval)

product_lists.apply(len).describe()

count    602754.000000
mean         17.819404
std           9.303519
min           1.000000
25%           9.000000
50%          25.000000
75%          25.000000
max          25.000000
Name: product_skus_hash, dtype: float64

In [7]:
clicked_lists = search["clicked_skus_hash"].dropna().apply(ast.literal_eval)

clicked_lists.apply(len).describe()

count    179495.000000
mean          2.184947
std           5.524525
min           1.000000
25%           1.000000
50%           1.000000
75%           2.000000
max         847.000000
Name: clicked_skus_hash, dtype: float64

In [9]:
def clicked_in_results(row):
    if pd.isna(row["product_skus_hash"]) or pd.isna(row["clicked_skus_hash"]):
        return None
    
    products = set(ast.literal_eval(row["product_skus_hash"]))
    clicked = set(ast.literal_eval(row["clicked_skus_hash"]))
    
    return clicked.issubset(products)

In [11]:
search["click_in_results"] = search.apply(
    clicked_in_results,
    axis=1
)

In [12]:
search["click_in_results"].value_counts(dropna=False)

click_in_results
None     640144
True     161873
False     17499
Name: count, dtype: int64

In [15]:
mismatch = search[
    search["click_in_results"] == False
]

mismatch[
    ["session_id_hash",
     "product_skus_hash",
     "clicked_skus_hash"]
].head(10)

,session_id_hash,product_skus_hash,clicked_skus_hash
12,77d604ce112a107ffe3e60566778d090a0b756bcfb0a3e...,['6c792545216e765efc2cfb6173fa17f833436116c703...,['20e8f1c4051a6c55122bd00f25f92f91b5f125497b79...
76,036d73f68c46108491dbd5ac4b36c5d7778706d9865fa0...,['53c5c9d0002590596ce079639cc39b075f185fd5a1c5...,['53c5c9d0002590596ce079639cc39b075f185fd5a1c5...
150,a5006c18c4e7af21a9db1838ac65d8a604f30749d3786b...,['1474045e3508b9b1b4986630cc462acf540aef4f057a...,['e0ccd39b7e6ad8e211283a9bdb9194786c64ef388698...
153,ff4525283a309b01d20a748547ea3cc4770bb12644406f...,['2a59f96e7bf5fc4882893cea3ec108beb1990c83eef7...,['f8c02189903e94c3aaf55a8b1070b39b00be438feb11...
155,ff4525283a309b01d20a748547ea3cc4770bb12644406f...,['851dc27d1cb392ca7d400023af163cdf9dedff368f9a...,['5589602aafd42abc5954b84e0d6605e5ad23173c85b7...
303,6f76fee8ca11f8a0bd169ef60437f01a975c7e4c97f8f6...,['c8a0660bd3c6a99b57cf3f64a22246b6ac60961c41b4...,['2d63efb713bb9ad10f6f8a69fce2abffc44037ac7f7b...
309,13e707e3faa1c1c8cee9d00b309029071892cede37d221...,['d97cb1147901653fd77c4061847fa22d08eb2fedc64a...,['6414b783f06559bf871feb5f5ee30b1c5e5dd43fcc57...
323,bef5c01c7208693e1078a7828116047eaed441d5285f63...,['b630310dcf592305123541c8255e19da06a266ee0ac1...,['24a9d54831a8bdfde0088504faaba145a18421db3b00...
325,7babe6ed9aaeb34339fc97e9f17be5cd533cb08439c456...,['b630310dcf592305123541c8255e19da06a266ee0ac1...,['5cd8cacb12c05499368dac0f4bbfa0175a398484185d...
482,340ab570a47daf41b1b773816bb3a94a6db2bfb6a899ee...,['0affe61b3bab0071624a035ddc54b45744fc8c40f984...,['9d48ff983ac3883611dd47eb488ce49ebf70f7738c6a...

In [17]:
def click_match_stats(row):
    if pd.isna(row["product_skus_hash"]) or pd.isna(row["clicked_skus_hash"]):
        return pd.Series({
            "clicked_count": None,
            "matched_clicks": None
        })

    products = set(ast.literal_eval(row["product_skus_hash"]))
    clicked = set(ast.literal_eval(row["clicked_skus_hash"]))

    return pd.Series({
        "clicked_count": len(clicked),
        "matched_clicks": len(clicked.intersection(products))
    })

In [19]:
search[["clicked_count", "matched_clicks"]] = search.apply(
    click_match_stats,
    axis=1
)

In [20]:
search[
    search["clicked_count"].notna()
][["clicked_count", "matched_clicks"]].head(20)

     clicked_count  matched_clicks
12             1.0             0.0
13             1.0             1.0
18             2.0             2.0
19             1.0             1.0
22             1.0             1.0
31             1.0             1.0
32             1.0             1.0
43             1.0             1.0
45             1.0             1.0
46             1.0             1.0
47             1.0             1.0
49             1.0             1.0
63             1.0             1.0
73             2.0             2.0
75             3.0             3.0
76             7.0             6.0
100            2.0             2.0
103            1.0             1.0
136            1.0             1.0
139            1.0             1.0

In [23]:
search["match_ratio"] = (
    search["matched_clicks"] /
    search["clicked_count"]
)

In [25]:
search["match_ratio"].describe()

count    179372.000000
mean          0.922494
std           0.251456
min           0.000000
25%           1.000000
50%           1.000000
75%           1.000000
max           1.000000
Name: match_ratio, dtype: float64

In [27]:
search["match_category"] = np.select(
    [
        search["match_ratio"] == 1,
        (search["match_ratio"] > 0) & (search["match_ratio"] < 1),
        search["match_ratio"] == 0
    ],
    [
        "complete_match",
        "partial_match",
        "no_match"
    ],
    default="not_applicable"
)

In [29]:
search["match_category"].value_counts(dropna=False)

match_category
not_applicable    640144
complete_match    161873
no_match           10919
partial_match       6580
Name: count, dtype: int64

In [31]:
products["price_bucket"].value_counts(dropna=False).sort_index()

price_bucket
1.0      3198
2.0      3103
3.0      3350
4.0      3409
5.0      3086
6.0      3079
7.0      3191
8.0      3183
9.0      3238
10.0     3201
NaN     34348
Name: count, dtype: int64

In [33]:
products.duplicated("product_sku_hash").sum()

0

In [35]:
browsing.duplicated().sum()

1800

In [37]:
search.duplicated().sum()

0

In [39]:
duplicates = browsing[
    browsing.duplicated(keep=False)
]

duplicates.sort_values(
    ["session_id_hash", "server_timestamp_epoch_ms"]
).head(20)

,session_id_hash,event_type,product_action,product_sku_hash,server_timestamp_epoch_ms,hashed_url
34350536,00336e76b824489c441a0f52b84d8e0c3fd5434083f4b2...,event_product,purchase,87351dcfd979ed56d9c356c6a393d7f0688e1825f2191f...,1554845569605,e396b36a40f2c41d259a45b80e10cd113eb0bf7540b73f...
34350537,00336e76b824489c441a0f52b84d8e0c3fd5434083f4b2...,event_product,purchase,87351dcfd979ed56d9c356c6a393d7f0688e1825f2191f...,1554845569605,e396b36a40f2c41d259a45b80e10cd113eb0bf7540b73f...
5234802,004b2ce03537d5db408260b694fe592f6d7fa5c5139199...,event_product,purchase,c57eca9e486cba19a2980d4da7b2033b20ec9898f8bdb3...,1550432025419,e396b36a40f2c41d259a45b80e10cd113eb0bf7540b73f...
5234803,004b2ce03537d5db408260b694fe592f6d7fa5c5139199...,event_product,purchase,c57eca9e486cba19a2980d4da7b2033b20ec9898f8bdb3...,1550432025419,e396b36a40f2c41d259a45b80e10cd113eb0bf7540b73f...
29074269,00555d2bd3ebdcee27949c50e8ebb2572d2f45084497a9...,pageview,NaN,NaN,1547862143607,fc75a5639be994cca42175a7de0acc898355a6eca257df...
29074270,00555d2bd3ebdcee27949c50e8ebb2572d2f45084497a9...,pageview,NaN,NaN,1547862143607,fc75a5639be994cca42175a7de0acc898355a6eca257df...
29074271,00555d2bd3ebdcee27949c50e8ebb2572d2f45084497a9...,pageview,NaN,NaN,1547862143607,fc75a5639be994cca42175a7de0acc898355a6eca257df...
16091569,00bc9520fbef80c37d666f8e57a6605ea2a77ff5bb7a2b...,pageview,NaN,NaN,1550184573051,433b0e71df1fe9a8d1f45647545701f6108414c40eef76...
16091570,00bc9520fbef80c37d666f8e57a6605ea2a77ff5bb7a2b...,pageview,NaN,NaN,1550184573051,433b0e71df1fe9a8d1f45647545701f6108414c40eef76...
7371226,00dbf1ff02c501dc05109a38abe4da5a8148cfa068391e...,event_product,purchase,14508c22da411b84da36e212e140e78c362bcdb04c5ee4...,1554636505391,e396b36a40f2c41d259a45b80e10cd113eb0bf7540b73f...
7371227,00dbf1ff02c501dc05109a38abe4da5a8148cfa068391e...,event_product,purchase,14508c22da411b84da36e212e140e78c362bcdb04c5ee4...,1554636505391,e396b36a40f2c41d259a45b80e10cd113eb0bf7540b73f...
31024981,010842a92945ce362856184929d76568b3e5f2cae2943c...,event_product,purchase,b4a28f880409c1ce5c6a79408341c34602bfc0ff0cf011...,1550842899606,e396b36a40f2c41d259a45b80e10cd113eb0bf7540b73f...
31024982,010842a92945ce362856184929d76568b3e5f2cae2943c...,event_product,purchase,b4a28f880409c1ce5c6a79408341c34602bfc0ff0cf011...,1550842899606,e396b36a40f2c41d259a45b80e10cd113eb0bf7540b73f...
26937640,014a2ba439fcfa83db2a5b38febbec6b73c77ae139dd19...,pageview,NaN,NaN,1549330909393,38f5bd3c9a1cc5b39e6b965f1aa6c565737f58e19a560a...
26937641,014a2ba439fcfa83db2a5b38febbec6b73c77ae139dd19...,pageview,NaN,NaN,1549330909393,38f5bd3c9a1cc5b39e6b965f1aa6c565737f58e19a560a...
9718317,01c8d2ce8357873dc31cb37a3c5ef594b5f818e9918360...,pageview,NaN,NaN,1550893926189,1e6d71a6ec1fa0c1ddb04778f836014669c6688a70456a...
9718318,01c8d2ce8357873dc31cb37a3c5ef594b5f818e9918360...,pageview,NaN,NaN,1550893926189,1e6d71a6ec1fa0c1ddb04778f836014669c6688a70456a...
9718319,01c8d2ce8357873dc31cb37a3c5ef594b5f818e9918360...,event_product,detail,201e9d4c044b87dd80a6156b3fc38143c2dc90d964aeb9...,1550893926189,1e6d71a6ec1fa0c1ddb04778f836014669c6688a70456a...
9718320,01c8d2ce8357873dc31cb37a3c5ef594b5f818e9918360...,event_product,detail,201e9d4c044b87dd80a6156b3fc38143c2dc90d964aeb9...,1550893926189,1e6d71a6ec1fa0c1ddb04778f836014669c6688a70456a...
19118766,025d5e125ff23cdc0ea1b9645f767cf4abe6d4ded957d0...,pageview,NaN,NaN,1551990720574,10cf8acdd90cc03246e1fd01630637d89d861237b14cbe...

In [41]:
duplicates["product_action"].value_counts(dropna=False)

product_action
NaN         1416
purchase    1167
detail       657
remove       162
add           30
Name: count, dtype: int64

In [43]:
duplicates["event_type"].value_counts(dropna=False)

event_type
event_product    2016
pageview         1416
Name: count, dtype: int64

In [45]:
browsing = browsing.drop_duplicates().copy()

In [46]:
browsing.duplicated().sum()

0

In [49]:
browsing["event_time"] = pd.to_datetime(
    browsing["server_timestamp_epoch_ms"],
    unit="ms"
)

search["search_time"] = pd.to_datetime(
    search["server_timestamp_epoch_ms"],
    unit="ms"
)

In [50]:
browsing[
    ["server_timestamp_epoch_ms", "event_time"]
].head()

   server_timestamp_epoch_ms              event_time
0              1550885210881 2019-02-23 01:26:50.881
1              1550885213307 2019-02-23 01:26:53.307
2              1550885213307 2019-02-23 01:26:53.307
3              1550885215484 2019-02-23 01:26:55.484
4              1550885215484 2019-02-23 01:26:55.484

In [53]:
search["search_id"] = range(1, len(search) + 1)

In [55]:
search[
    ["search_id", "session_id_hash", "search_time"]
].head()

,search_id,session_id_hash,search_time
0,1,48fade624d47870058ce07dd789ccc04e46c70c0fa2a1b...,2019-01-27 07:46:34.779
1,2,8731ca84ff7bb8cb647531d54e64feedb2519b4a7792a7...,2019-01-23 20:52:43.869
2,3,9be980708345944960645d03606ea83b637cae9106b705...,2019-01-31 12:33:17.295
3,4,9be980708345944960645d03606ea83b637cae9106b705...,2019-01-31 12:33:58.268
4,5,9be980708345944960645d03606ea83b637cae9106b705...,2019-01-31 12:34:53.827

In [57]:

search["product_list"] = (
    search["product_skus_hash"]
    .dropna()
    .apply(ast.literal_eval)
)

In [58]:
search["product_list"] = search["product_skus_hash"].apply(
    lambda x: ast.literal_eval(x) if pd.notna(x) else []
)

In [59]:
search[
    ["product_skus_hash", "product_list"]
].head()

,product_skus_hash,product_list
0,NaN,[]
1,['9ee9ffd7e2529a65f9a0b0c9eaae6330df85cf2e3af3...,[9ee9ffd7e2529a65f9a0b0c9eaae6330df85cf2e3af33...
2,['7cc72dbed53bab78ec6a62feaa5052a7a1db7d201664...,[7cc72dbed53bab78ec6a62feaa5052a7a1db7d201664b...
3,['62c4ddab6c1c81c74d315376b3c0dc7768c0286b3dc6...,[62c4ddab6c1c81c74d315376b3c0dc7768c0286b3dc6f...
4,['2a0ee2924feabeec35e21e8fcb4d5b0684d190e46cef...,[2a0ee2924feabeec35e21e8fcb4d5b0684d190e46cef7...

In [63]:
search["clicked_list"] = search["clicked_skus_hash"].apply(
    lambda x: ast.literal_eval(x) if pd.notna(x) else []
)

In [64]:
result_rows = []

for _, row in search.iterrows():
    clicked = set(row["clicked_list"])

    for sku in row["product_list"]:
        result_rows.append({
            "search_id": row["search_id"],
            "product_sku_hash": sku,
            "clicked": 1 if sku in clicked else 0
        })

search_results = pd.DataFrame(result_rows)

In [66]:
search_results.head(20)

    search_id                                   product_sku_hash  clicked
0           2  9ee9ffd7e2529a65f9a0b0c9eaae6330df85cf2e3af33e...        0
1           2  4367f3b54eded7d6f8800a381dec2970e3751dc9c14a1b...        0
2           2  54f0f45519bbff585a55899d88e4cca03e61b88f90783e...        0
3           3  7cc72dbed53bab78ec6a62feaa5052a7a1db7d201664bb...        0
4           3  3da7ad7f203d5ed2dfb6db08065266fa49c700e028e8bb...        0
5           3  664fae425faebb61c083606e059bf6e28cc86adcd047fd...        0
6           3  05924a7ed72204fbde3a21d7833da2ee23a9dff7a8e271...        0
7           3  f0ff35ed8a1feb70e2a5d1ec178fae47452177815ef5d7...        0
8           3  bd2f17bff45a72e4c9d7f5916dd930a87bffc8046cc86f...        0
9           3  d627da3aba5e8a7a6fba3e9774fd896fd163a3fd284d44...        0
10          4  62c4ddab6c1c81c74d315376b3c0dc7768c0286b3dc6f1...        0
11          4  e05cd95cd5bbf9452dc76e5c097d928b7b8a21a553bd32...        0
12          4  18d0cbb6fcd4c67c6e4a863ab86a18bd4f2558e8b0b92f...        0
13          4  c7f9523426ecc6ce5d988966f36c906d04e84006c90753...        0
14          4  1378d1490ae96c2e576db5d78e1640d863d64e97b08410...        0
15          4  30c66a2327b0c1426eda7692de92b6ee3d3aa53bade271...        0
16          4  f6ec1b20eac2a3f3cfc580d14ae5a47ca80642d0545dc9...        0
17          4  08159904b78aa3502e211661ee2fd972d6fdb15afd1e04...        0
18          4  43a258d5f864cf1977bbd5878a0be6ace9cc8d0bbe3e6b...        0
19          4  92336743a91d962e44a7dd38c987b7c89a1379759516dd...        0

In [69]:
search_events = search[
    [
        "search_id",
        "session_id_hash",
        "query_vector",
        "server_timestamp_epoch_ms",
        "search_time"
    ]
].copy()

In [71]:
search_results.shape

(10740717, 3)

In [73]:
search_results.head()

   search_id                                   product_sku_hash  clicked
0          2  9ee9ffd7e2529a65f9a0b0c9eaae6330df85cf2e3af33e...        0
1          2  4367f3b54eded7d6f8800a381dec2970e3751dc9c14a1b...        0
2          2  54f0f45519bbff585a55899d88e4cca03e61b88f90783e...        0
3          3  7cc72dbed53bab78ec6a62feaa5052a7a1db7d201664bb...        0
4          3  3da7ad7f203d5ed2dfb6db08065266fa49c700e028e8bb...        0

In [75]:
result_rows = []

for _, row in search.iterrows():

    returned_skus = set(row["product_list"])
    clicked_skus = set(row["clicked_list"])

    all_skus = returned_skus | clicked_skus

    for sku in all_skus:
        result_rows.append({
            "search_id": row["search_id"],
            "product_sku_hash": sku,
            "result_present": int(sku in returned_skus),
            "clicked": int(sku in clicked_skus)
        })

search_results = pd.DataFrame(result_rows)

In [76]:
search_results[["result_present", "clicked"]].value_counts()

result_present  clicked
1               0          10507595
                1            233098
0               1             23711
Name: count, dtype: int64

In [79]:
search_results.shape

(10764404, 4)

In [81]:
browsing.columns

Index(['session_id_hash', 'event_type', 'product_action', 'product_sku_hash',
       'server_timestamp_epoch_ms', 'hashed_url', 'event_time'],
      dtype='object')

In [83]:
search.columns

Index(['session_id_hash', 'query_vector', 'clicked_skus_hash',
       'product_skus_hash', 'server_timestamp_epoch_ms', 'click_in_results',
       'clicked_count', 'matched_clicks', 'match_ratio', 'match_category',
       'search_time', 'search_id', 'product_list', 'clicked_list'],
      dtype='object')

In [85]:
search_events.columns

Index(['search_id', 'session_id_hash', 'query_vector',
       'server_timestamp_epoch_ms', 'search_time'],
      dtype='object')

In [87]:
search_results.columns

Index(['search_id', 'product_sku_hash', 'result_present', 'clicked'], dtype='object')

In [89]:
products.columns

Index(['product_sku_hash', 'description_vector', 'category_hash',
       'image_vector', 'price_bucket'],
      dtype='object')

In [91]:
browsing[
    ["session_id_hash",
     "event_type",
     "product_action",
     "product_sku_hash",
     "event_time"]
].head()

,session_id_hash,event_type,product_action,product_sku_hash,event_time
0,20c458b802f6ea9374783bfc528b19421be977a6769785...,event_product,detail,d5157f8bc52965390fa21ad5842a8502bc3eb8b0930f3f...,2019-02-23 01:26:50.881
1,20c458b802f6ea9374783bfc528b19421be977a6769785...,event_product,detail,61ef3869355b78e11011f39fc7ac8f8dfb209b3442a9d5...,2019-02-23 01:26:53.307
2,20c458b802f6ea9374783bfc528b19421be977a6769785...,pageview,NaN,NaN,2019-02-23 01:26:53.307
3,20c458b802f6ea9374783bfc528b19421be977a6769785...,event_product,detail,d5157f8bc52965390fa21ad5842a8502bc3eb8b0930f3f...,2019-02-23 01:26:55.484
4,20c458b802f6ea9374783bfc528b19421be977a6769785...,pageview,NaN,NaN,2019-02-23 01:26:55.484

In [111]:
print("Product SKU max:", products["product_sku_hash"].str.len().max())

Product SKU max: 64

In [93]:
products.to_csv(r"D:/Downloads/Products.csv", index=False)

In [95]:
search_events.to_csv("D:/Downloads/Search_events.csv", index=False)

In [96]:
search_results.to_csv("D:/Downloads/Search_results.csv", index=False)

In [99]:
browsing.to_csv("D:/Downloads/Browsing.csv", index=False)

In [101]:
products.head()

,product_sku_hash,description_vector,category_hash,image_vector,price_bucket
0,26ce7b47f4c46e4087e83e54d2f7ddc7ea57862fed2e2a...,NaN,NaN,NaN,NaN
1,6383992be772b204a9ab75f86c86f5583d1bdd1222952d...,NaN,NaN,NaN,NaN
2,a2c3e2430c6ef9770b903ad08fa067a6b2b9db28f06e1b...,"[0.27629122138023376, -0.15763211250305176, 0....",06fa312761d4b39e2f649781514ac69a4c1505c221fc46...,"[340.3592564184389, -220.19025864725685, 154.0...",7.0
3,1028ef615e425c328e7b95010dfb1fb93cf63749a1bc80...,"[0.4058118760585785, -0.03595402091741562, 0.2...",115a6a7017ee55752b8487c77dfde92b0d501d10a2e69c...,"[180.3463662921092, 222.702322343354, -8.88703...",8.0
4,9870c682d0d52d635501249da0eeaa118fad430b695ea1...,"[-0.3206155300140381, 0.01991105079650879, 0.0...",0665a81d19c89281cc00e7f7d779ded2ed42c933838602...,"[-114.81079301576219, 84.55770104232334, 85.51...",2.0

In [103]:
products['price_bucket'] = pd.to_numeric(products['price_bucket'], errors='coerce')

In [105]:

products['price_bucket'] = products['price_bucket'].where(products['price_bucket'].notna(), None)

In [109]:
products.head()

,product_sku_hash,description_vector,category_hash,image_vector,price_bucket
0,26ce7b47f4c46e4087e83e54d2f7ddc7ea57862fed2e2a...,NaN,NaN,NaN,NaN
1,6383992be772b204a9ab75f86c86f5583d1bdd1222952d...,NaN,NaN,NaN,NaN
2,a2c3e2430c6ef9770b903ad08fa067a6b2b9db28f06e1b...,"[0.27629122138023376, -0.15763211250305176, 0....",06fa312761d4b39e2f649781514ac69a4c1505c221fc46...,"[340.3592564184389, -220.19025864725685, 154.0...",7.0
3,1028ef615e425c328e7b95010dfb1fb93cf63749a1bc80...,"[0.4058118760585785, -0.03595402091741562, 0.2...",115a6a7017ee55752b8487c77dfde92b0d501d10a2e69c...,"[180.3463662921092, 222.702322343354, -8.88703...",8.0
4,9870c682d0d52d635501249da0eeaa118fad430b695ea1...,"[-0.3206155300140381, 0.01991105079650879, 0.0...",0665a81d19c89281cc00e7f7d779ded2ed42c933838602...,"[-114.81079301576219, 84.55770104232334, 85.51...",2.0

In [107]:
products.to_csv("D:/Downloads/Products_new.csv", index=False)

In [111]:
search_results.head()

,search_id,product_sku_hash,result_present,clicked
0,2,4367f3b54eded7d6f8800a381dec2970e3751dc9c14a1b...,1,0
1,2,54f0f45519bbff585a55899d88e4cca03e61b88f90783e...,1,0
2,2,9ee9ffd7e2529a65f9a0b0c9eaae6330df85cf2e3af33e...,1,0
3,3,05924a7ed72204fbde3a21d7833da2ee23a9dff7a8e271...,1,0
4,3,3da7ad7f203d5ed2dfb6db08065266fa49c700e028e8bb...,1,0

In [7]:
rank_rows = []

for _, row in search.iterrows():
    for rank, sku in enumerate(row["product_list"], start=1):
        rank_rows.append({
            "search_id": row["search_id"],
            "product_sku_hash": sku,
            "result_rank": rank
        })

search_result_rank = pd.DataFrame(rank_rows)

search_result_rank.head()

KeyError: 'product_list'